"use client";
import {useCallback,useEffect,useState} from 'react';
import s from './admin.module.css';
type Campaign={id:string;customerId:string;name:string;status:string;budget:number;metrics:{impressions:number;clicks:number;cost:number;conversions:number;averageCpc:number};position:{impressionShare:number;rankLostShare:number;budgetLostShare:number;topShare:number;absoluteTopShare:number};biddingStrategy:string};
type Data={connected:boolean;siteHost:string;campaigns:Campaign[];updatedAt?:string};
const n=(v:number)=>Math.round(v).toLocaleString('ko-KR'),pct=(v:number)=>Number.isFinite(v)?(v*100).toFixed(1)+'%':'—';
const strategy=(v:string)=>({MAXIMIZE_CONVERSIONS:'전환수 최대화',MAXIMIZE_CONVERSION_VALUE:'전환가치 최대화',TARGET_CPA:'목표 CPA',TARGET_ROAS:'목표 ROAS',MANUAL_CPC:'수동 CPC'}[v]||v||'확인 중');
export default function GoogleAds({session}:{session:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[refresh,setRefresh]=useState(0);
 const load=useCallback(async(signal:AbortSignal)=>{const r=await fetch('/api/admin/google-ads',{headers:{authorization:`Bearer ${session}`},cache:'no-store',signal});const d=await r.json();if(!r.ok)throw Error(d.error);return d as Data;},[session]);
 useEffect(()=>{const c=new AbortController();load(c.signal).then(d=>{if(!c.signal.aborted){setData(d);setError('');}}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort();},[load,refresh]);
 async function connect(){setBusy('connect');setError('');try{const r=await fetch('/api/admin/google-ads',{method:'POST',headers:{authorization:`Bearer ${session}`,'content-type':'application/json'},body:JSON.stringify({action:'connect'})});const d=await r.json();if(!r.ok)throw Error(d.error);window.location.assign(d.url);}catch(e){setError(e instanceof Error?e.message:'연결을 시작하지 못했습니다.');setBusy('');}}
 async function toggle(c:Campaign){const action=c.status==='ENABLED'?'pause':'enable';if(!window.confirm(`${c.name} 광고를 ${action==='pause'?'끌까요?':'켤까요?'}\n일예산 ${n(c.budget)}원`))return;setBusy(c.id);try{const r=await fetch('/api/admin/google-ads',{method:'POST',headers:{authorization:`Bearer ${session}`,'content-type':'application/json'},body:JSON.stringify({action,campaignId:c.id,expectedStatus:c.status})});const d=await r.json();if(!r.ok)throw Error(d.error);setRefresh(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'변경에 실패했습니다.');}finally{setBusy('');}}
 return <section className={s.panel}><div className={s.sectionTitle}><div><h2>구글 광고</h2><p className={s.hint}>명진 계정 · 로켓보일러 전용 광고계정</p></div><button className={s.ghost} onClick={()=>setRefresh(v=>v+1)}>↻ 새로고침</button></div>{error&&<p role="alert" className={s.error}>{error}</p>}{!data&&!error&&<p className={s.hint}>구글 광고를 조회하고 있습니다.</p>}{data&&!data.connected&&<div className={s.sectionTitle}><p className={s.notice}>Google Ads 승인을 한 번 완료하면 여기에서 바로 켜고 끌 수 있습니다.</p><button className={s.primary} disabled={busy==='connect'} onClick={()=>void connect()}>{busy==='connect'?'연결 중…':'명진 Google Ads 연결'}</button></div>}{data?.connected&&!data.campaigns.length&&<p className={s.notice}>로켓보일러 광고계정에 표시할 캠페인이 없습니다.</p>}{data?.campaigns.map(c=><div key={c.id}><div className={s.metrics}><article data-accent="gold"><span>최근 30일 광고비</span><strong>{n(c.metrics.cost)}<small>원</small></strong><em>평균 CPC {n(c.metrics.averageCpc)}원</em></article><article><span>노출점유율</span><strong>{pct(c.position.impressionShare)}</strong><em>상단 {pct(c.position.topShare)}</em></article><article><span>순위 손실</span><strong>{pct(c.position.rankLostShare)}</strong><em>예산 손실 {pct(c.position.budgetLostShare)}</em></article><article><span>전환</span><strong>{n(c.metrics.conversions)}<small>건</small></strong><em>{strategy(c.biddingStrategy)}</em></article></div><div className={s.sectionTitle}><div><b>{c.name}</b><p className={s.hint}>계정 {c.customerId} · {c.status==='ENABLED'?'광고 ON':'광고 OFF'} · 일예산 {n(c.budget)}원</p></div><div className={s.stockActions}><button className={s.ghost} onClick={()=>window.alert(`${c.name}\n노출점유율 ${pct(c.position.impressionShare)} · 상단 ${pct(c.position.topShare)}\n순위 손실 ${pct(c.position.rankLostShare)} · 예산 손실 ${pct(c.position.budgetLostShare)}\n입찰 방식 ${strategy(c.biddingStrategy)}`)}>순위·입찰 점검</button><button className={c.status==='ENABLED'?s.ghost:s.primary} disabled={busy===c.id} onClick={()=>void toggle(c)}>{busy===c.id?'반영 중…':c.status==='ENABLED'?'광고 끄기':'광고 켜기'}</button></div></div></div>)}</section>;
}
