"use client";
import {useEffect,useState} from 'react';
import {profitCatalog} from './profit';
import s from './admin.module.css';
export default function LeadSale({id,session}:{id:string;session:string}){
  const [data,setData]=useState<{sale_sku:string|null;sale_amount:number|null;store_order_id:string|null}|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();fetch('/api/admin/earnings/lead?id='+encodeURIComponent(id),{headers:{authorization:`Bearer ${session}`},signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>controller.abort();},[id,session]);
  async function save(){setBusy(true);try{const r=await fetch('/api/admin/earnings/lead',{method:'POST',headers:{authorization:`Bearer ${session}`,'content-type':'application/json'},body:JSON.stringify({id,...data})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage('저장했습니다. 설치 완료 시 매출·수익에 자동 반영됩니다.');}catch(e){setMessage(e instanceof Error?e.message:'저장 오류');}finally{setBusy(false);}}
  return <section className={s.detailSection}><h3>판매 확정 정보</h3><p className={s.hint}>홈페이지는 상담 접수이므로 실제로 판매한 모델과 금액만 이곳에 확정하세요. 매출·수익에서 다시 입력할 필요가 없습니다.</p>{data&&<div className={s.setupForm}><label className={s.field}>판매 모델<select disabled={busy} value={data.sale_sku||''} onChange={e=>setData({...data,sale_sku:e.target.value||null})}><option value="">확정 전</option>{profitCatalog.map(p=><option key={p.sku} value={p.sku}>{p.brand} {p.model}</option>)}</select></label><label className={s.field}>실제 판매금액 · 원<input type="number" min="0" max="100000000" disabled={busy} value={data.sale_amount??''} onChange={e=>setData({...data,sale_amount:e.target.value===''?null:Number(e.target.value)})}/></label><details><summary>네이버 주문으로 결제한 상담</summary><label className={s.field}>네이버 상품주문번호<input disabled={busy} value={data.store_order_id||''} onChange={e=>setData({...data,store_order_id:e.target.value||null})}/><small>연결하면 이 상담은 중복 매출에서 제외하고 네이버 결제액으로 집계합니다.</small></label></details><button className={s.primary} disabled={busy} onClick={()=>void save()}>판매 정보 적용</button></div>}<p role="status">{message}</p></section>;
}
