"use client";
import {useCallback,useEffect,useState} from 'react';
import {koreaDate} from './shared';
import s from './admin.module.css';
import GoogleAds from './GoogleAds';
type Stats={impCnt:number;clkCnt:number;salesAmt:number};
type Data={connected:boolean;customerId:string;siteHost:string;excludedMixed:number;channelReasons:string[];parentCampaigns:{id:string;name:string;status:string;paused:boolean}[];campaigns:(Stats&{id:string;campaignId:string;name:string;status:string;statusReason:string;paused:boolean;type:string})[];totals:Stats;leads:{naver:number;google:number;unknown:number;naverCompleted:number};updatedAt:string};
const n=(v:number)=>v.toLocaleString('ko-KR');
const status=(value:string,paused:boolean)=>paused?'중지':({ELIGIBLE:'노출 가능',PAUSED:'중지',DELETED:'삭제',PENDING:'검토 중',LIMITED:'노출 제한'}[value]||value||'상태 확인');
export default function NaverAds({session}:{session:string}){
 const [toggling,setToggling]=useState('');const [toggleNotice,setToggleNotice]=useState('');
 const [since,setSince]=useState(()=>koreaDate(new Date(Date.now()-6*86400000)));const [until,setUntil]=useState(koreaDate());const [period,setPeriod]=useState({since,until});const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [refresh,setRefresh]=useState(0);
 const fetchData=useCallback(async(signal:AbortSignal)=>{const r=await fetch('/api/admin/naver-ads?'+new URLSearchParams(period),{headers:{authorization:`Bearer ${session}`},cache:'no-store',signal});const d=await r.json();if(!r.ok)throw Error(d.error);return d as Data;},[period,session]);
 useEffect(()=>{const c=new AbortController();fetchData(c.signal).then(d=>{if(!c.signal.aborted){setData(d);setError('');setLoading(false);}}).catch(e=>{if(!c.signal.aborted){setError(e.message);setLoading(false);setData(null);}});return()=>c.abort();},[fetchData,refresh]);
 function submit(){setLoading(true);setData(null);setError('');setPeriod({since,until});setRefresh(v=>v+1);}
 async function toggleCampaign(c:Data['parentCampaigns'][number]){if(toggling)return;setToggling(c.id);setToggleNotice('');try{const r=await fetch('/api/admin/naver-ads',{method:'POST',headers:{authorization:`Bearer ${session}`,'content-type':'application/json'},body:JSON.stringify({action:'campaign-toggle',id:c.id,paused:!c.paused,expectedPaused:c.paused})});const d=await r.json();if(!r.ok)throw Error(d.error);setToggleNotice(d.paused?'네이버 광고 전체를 OFF로 변경했습니다.':'네이버 광고 전체를 ON으로 변경했습니다.');setRefresh(v=>v+1);}catch(e){setToggleNotice(e instanceof Error?e.message:'설정 변경에 실패했습니다.');}finally{setToggling('');}}
 async function optimize(){
  if(toggling)return;setToggling('optimize');setToggleNotice('');
  try{const call=async(dryRun:boolean)=>{const r=await fetch('/api/admin/naver-ads',{method:'POST',headers:{authorization:`Bearer ${session}`,'content-type':'application/json'},body:JSON.stringify({action:'optimize',dryRun})});const d=await r.json();if(!r.ok)throw Error(d.error);return d.result;};const preview=await call(true);if(!preview.targetCount){setToggleNotice('현재 키워드 입찰가가 모바일 예상 3위 범위에 맞습니다.');return;}if(!window.confirm(`모바일 예상 3위 기준으로 ${preview.targetCount}개 키워드를 조정할까요?\n최대 입찰 3,500원 · 한 번에 최대 20% 또는 500원`))return;const result=await call(false);setToggleNotice(`${result.changedCount}개 키워드 입찰가를 조정했습니다.`);setRefresh(v=>v+1);}catch(e){setToggleNotice(e instanceof Error?e.message:'입찰 점검에 실패했습니다.');}finally{setToggling('');}
 }
 const totals=data?.connected?data.totals:null;
 return <div className={s.profitWorkspace}><section className={s.panel}><div className={s.sectionTitle}><div><h2>네이버 검색광고</h2><p className={s.hint}>{data?.connected?`계정 ${data.customerId} · 연결됨`:'광고 계정 연결 확인'}</p></div><div className={s.stockActions}><button type="button" className={s.primary} disabled={!data?.connected||Boolean(toggling)||loading} onClick={()=>void optimize()}>{toggling==='optimize'?'입찰 계산 중…':'모바일 3위 입찰 점검'}</button><a className={s.externalLink} href="https://searchad.naver.com/" target="_blank" rel="noreferrer">네이버 광고 관리 ↗</a></div></div><form className={s.setupForm} onSubmit={e=>{e.preventDefault();submit();}}><div className={s.dateInputs}><label className={s.field}>시작일<input aria-label="광고 시작일" type="date" required value={since} max={until} onChange={e=>setSince(e.target.value)}/></label><label className={s.field}>종료일<input aria-label="광고 종료일" type="date" required value={until} min={since} max={koreaDate()} onChange={e=>setUntil(e.target.value)}/></label></div><div className={s.stockActions}>{[7,30].map(days=><button type="button" className={s.ghost} key={days} onClick={()=>{const end=koreaDate(),start=koreaDate(new Date(Date.now()-(days-1)*86400000));setSince(start);setUntil(end);setPeriod({since:start,until:end});setLoading(true);setData(null);setError('');setRefresh(v=>v+1);}}>최근 {days}일</button>)}<button className={s.primary} disabled={loading}>{loading?'조회 중…':'광고 현황 조회'}</button></div></form><p className={s.hint}>rocketboiler.vercel.app 연결 광고만 · 모바일 예상 3위 목표 · 최대 입찰 3,500원 · 최대 31일 · 오늘 통계는 집계 중일 수 있습니다.</p></section>
 {data?.connected&&data.channelReasons.includes('BUSINESS_CHANNEL_DISAPPROVED')&&<p className={s.notice}>로켓보일러 사이트 채널이 검수 보류 상태입니다. 네이버 광고 관리에서 검수 사유를 확인해 주세요.</p>}{data?.connected&&data.excludedMixed>0&&<p className={s.hint}>다른 사이트 URL이 섞였거나 연결 URL을 확인할 수 없는 그룹 {data.excludedMixed}개는 제외했습니다.</p>}
 {toggleNotice&&<p role="status" className={s.notice}>{toggleNotice}</p>}
 {data?.connected&&data.parentCampaigns.map(c=>{const serving=!c.paused;return <section className={`${s.panel} ${s.adMasterPanel}`} key={c.id}><div className={s.adMaster}><div className={s.adMasterCopy}><span className={s.adPlatform}>NAVER SEARCH ADS</span><div className={s.adStatusLine}><span className={s.adStatusDot} data-on={serving}/><h2>{serving?'광고 운영 중':'광고 꺼짐'}</h2><span className={s.adStatusBadge} data-on={serving}>{serving?'ON':'OFF'}</span></div><p>{serving?'로켓보일러 네이버 검색광고가 노출 가능한 상태입니다.':'상위 캠페인이 중지되어 광고그룹이 ON이어도 실제 광고는 노출되지 않습니다.'}</p><div className={s.adMeta}><span>캠페인 <b>{c.name}</b></span><span>광고그룹 <b>{data.campaigns.length}개</b></span></div></div><div className={s.adSwitchArea}><span>전체 광고</span><button type="button" role="switch" aria-checked={serving} aria-label={`네이버 전체 광고 ${serving?'끄기':'켜기'}`} className={s.adSwitch} data-on={serving} disabled={Boolean(toggling)||loading} onClick={()=>void toggleCampaign(c)}><span className={s.adSwitchKnob}/></button><strong>{toggling===c.id?'반영 중…':serving?'켜짐':'꺼짐'}</strong></div></div></section>})}
 {error&&<p role="alert" className={s.error}>{error}</p>}{data&&!data.connected&&<p className={s.notice}>등록된 네이버 검색광고 연결 정보가 없습니다.</p>}
 <div className={s.metrics}><article data-accent="gold"><span>광고비</span><strong>{totals?n(totals.salesAmt):'—'}<small>원</small></strong><em>이 사이트 연결 광고그룹 합계</em></article><article><span>노출</span><strong>{totals?n(totals.impCnt):'—'}<small>회</small></strong><em>네이버 검색광고 통계</em></article><article><span>클릭</span><strong>{totals?n(totals.clkCnt):'—'}<small>회</small></strong><em>평균 클릭비 {totals&&totals.clkCnt?n(Math.round(totals.salesAmt/totals.clkCnt))+'원':'—'}</em></article><article><span>클릭률</span><strong>{totals&&totals.impCnt?(totals.clkCnt/totals.impCnt*100).toFixed(2):totals?'0.00':'—'}<small>%</small></strong><em>클릭 ÷ 노출</em></article></div>
 <section className={s.panel}><div className={s.sectionTitle}><div><h2>광고그룹 상세</h2><p className={s.hint}>전체 ON/OFF는 위의 큰 스위치에서 관리합니다.</p></div><span>{data?.connected?data.campaigns.length:0}개</span></div><div className={s.tableScroll}><table className={`${s.table} ${s.mobileCards}`}><thead><tr><th>광고그룹·실제 상태</th><th>광고비</th><th>노출</th><th>클릭</th><th>클릭률</th></tr></thead><tbody>{data?.connected&&data.campaigns.map(c=>{const parentPaused=data.parentCampaigns.find(parent=>parent.id===c.campaignId)?.paused??true;const actualStatus=parentPaused?'캠페인 OFF로 노출 중지':c.paused?'광고그룹 OFF':status(c.status,c.paused);return <tr key={c.id}><td data-label="광고그룹"><b>{c.name}</b><small className={s.groupStatus} data-on={!parentPaused&&!c.paused}>{actualStatus}</small>{!parentPaused&&<small>{c.statusReason==='AD_UNDER_REVIEW'?'광고 검토 중':c.statusReason==='BUSINESS_CHANNEL_DISAPPROVED'?'사이트 검수 보류':c.statusReason==='ELIGIBLE'?'':c.statusReason}</small>}</td><td data-label="광고비">{n(c.salesAmt)}원</td><td data-label="노출">{n(c.impCnt)}회</td><td data-label="클릭">{n(c.clkCnt)}회</td><td data-label="클릭률">{c.impCnt?(c.clkCnt/c.impCnt*100).toFixed(2):'0.00'}%</td></tr>})}</tbody></table></div>{data?.connected&&!data.campaigns.length&&<p className={s.smallEmpty}>이 사이트에 연결된 광고그룹이 없습니다.</p>}{data?.connected&&totals?.impCnt===0&&<p className={s.hint}>선택 기간에 조회된 노출 실적이 없습니다.</p>}</section>
 <section className={s.panel}><div className={s.sectionTitle}><h2>홈페이지 상담 유입</h2><span>광고 조회와 같은 접수 기간</span></div><div className={s.attribution}><div><span>네이버 광고 유입</span><strong>{data?.connected?n(data.leads.naver):'—'}건</strong></div><div><span>그중 설치 완료</span><strong>{data?.connected?n(data.leads.naverCompleted):'—'}건</strong></div><div><span>구글 광고 유입</span><strong>{data?.connected?n(data.leads.google):'—'}건</strong></div></div><p className={s.hint}>사이트 유입 정보 기준이며 네이버 광고의 전환 보고서와 다릅니다. 사이트 전체 네이버 광고 유입으로, 광고 계정·캠페인별 상담 구분은 아직 적용되지 않았습니다. 샘플 상담은 제외합니다.</p></section>
 <GoogleAds session={session}/>
 {data?.connected&&<p className={s.hint}>최근 조회 {new Date(data.updatedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>}
 </div>;
}
