"use client";
import {useCallback,useEffect,useState} from 'react';
import {koreaDate} from './shared';
import type {Sale} from './earnings';
import s from './admin.module.css';
type Range={min:number;max:number};
type Model={sku:string;brand:string;model:string;cost:number|null;costSource:string;web:Range|null;naver:number|null;webProfit:Range|null};
type Data={defaultLabor:number;naverConnected:boolean;sales:Sale[];totals:{count:number;revenue:number;profit:number;missing:number;pending:number};models:Model[]};
const won=(n:number|null)=>n===null?'확인 필요':Math.round(n).toLocaleString('ko-KR')+'원';
const range=(v:Range|null)=>v?v.min===v.max?won(v.min):`${(v.min/10000).toFixed(1)}~${(v.max/10000).toFixed(1)}만 원`:'견적 확인';
const statusNames={sold:'판매 반영',pending:'판매 전',cancelled:'취소·반품',linked:'네이버에서 집계'};
export default function ProfitManager({session}:{session:string}){
  const [month,setMonth]=useState(koreaDate().slice(0,7));const [data,setData]=useState<Data|null>(null);const [brand,setBrand]=useState('');const [channel,setChannel]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  const fetchData=useCallback(async(signal?:AbortSignal)=>{const r=await fetch('/api/admin/earnings?month='+month,{headers:{authorization:`Bearer ${session}`},cache:'no-store',signal});const d=await r.json();if(!r.ok)throw Error(d.error);return d as Data;},[session,month]);
  async function reload(){const d=await fetchData();setData(d);setError('');}
  useEffect(()=>{const controller=new AbortController();fetchData(controller.signal).then(d=>{if(!controller.signal.aborted){setData(d);setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[fetchData]);
  async function save(action:'default'|'labor',labor:number,id?:string){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/earnings',{method:'POST',headers:{authorization:`Bearer ${session}`,'content-type':'application/json'},body:JSON.stringify({action,labor,id})});const d=await r.json();if(!r.ok)throw Error(d.error);await reload();setMessage(action==='default'?'신규 판매에 적용할 기본 기사비를 저장했습니다.':'기사비와 수익을 반영했습니다.');}catch(e){setError(e instanceof Error?e.message:'저장 오류');}finally{setBusy(false);}}
  const rows=data?.sales.filter(r=>!channel||r.channel===channel)||[];
  return <div className={s.profitWorkspace}>
    <section className={s.panel}><div className={s.sectionTitle}><div><h2>판매되면 자동으로 계산합니다</h2><p className={s.hint}>판매금액 − 매입 원가 − 기사비. 판매 채널의 금액을 그대로 사용합니다.</p></div><button className={s.ghost} disabled={busy} onClick={()=>void reload().catch(e=>setError(e.message))}>자동 집계 새로고침</button></div><div className={s.dateInputs}><label className={s.field}>기본 기사비 · 보일러 1대당<select aria-label="기본 기사비" disabled={!data||busy} value={data?.defaultLabor??80000} onChange={e=>void save('default',Number(e.target.value))}>{[80000,90000,100000].map(n=><option key={n} value={n}>{n/10000}만 원</option>)}</select><small>신규 판매와 아래 예상이익에 적용 · 기존 판매는 건별 변경</small></label><label className={s.field}>조회 월<input aria-label="매출 조회 월" type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setData(null);}}}/></label></div></section>
    {error&&<p role="alert" className={s.error}>{error}</p>}{message&&<p role="status" className={s.saveMessage}>{message}</p>}
    <div className={s.metrics}><article><span>판매금액</span><strong>{data?data.totals.revenue.toLocaleString():'—'}<small>원</small></strong><em>{data?.totals.count??0}건 · 금액 확인된 판매 합계</em></article><article data-accent="gold"><span>원가·기사비 차감 이익</span><strong>{data?data.totals.profit.toLocaleString():'—'}<small>원</small></strong><em>원가 참고표 기준 · 수수료·기타비용 차감 전</em></article><article><span>금액·모델 확인 필요</span><strong>{data?.totals.missing??'—'}<small>건</small></strong><em>확인 전 해당 건의 이익은 합계 제외</em></article><article><span>판매 전 상담·주문</span><strong>{data?.totals.pending??'—'}<small>건</small></strong><em>예상가를 확정 매출로 합산하지 않음</em></article></div>
    <section className={s.panel}><div className={s.sectionTitle}><h2>판매별 자동 정산</h2><select aria-label="판매 채널" value={channel} onChange={e=>setChannel(e.target.value)}><option value="">전체 채널</option><option value="web">홈페이지</option><option value="naver">네이버스토어</option></select></div><p className={s.hint}>홈페이지: 상담에서 판매 정보 확정 후 ‘완료’ 처리하면 반영됩니다. 네이버: 불러온 결제 완료 주문의 실제 결제액으로 반영됩니다. 중복·취소·반품은 제외합니다.</p>{data&&!data.naverConnected&&<p className={s.notice}>네이버 주문 연결은 보류 상태입니다. 연결 후 주문을 불러오면 판매가·원가·기사비가 자동 계산됩니다.</p>}<div className={s.tableScroll}><table className={`${s.table} ${s.mobileCards}`}><thead><tr><th>채널·모델</th><th>판매금액</th><th>매입 원가</th><th>기사비 · 대당</th><th>예상이익</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td data-label="판매"><b>{r.channel==='web'?'홈페이지':'네이버'} · {r.model}</b><small>{r.date} · {r.quantity}대 · {statusNames[r.status]}</small><small>{r.note}</small>{!r.sku&&<small>판매 모델 연결 필요</small>}</td><td data-label="판매금액">{won(r.amount)}</td><td data-label="매입 원가">{won(r.cost===null?null:r.cost*r.quantity)}</td><td data-label="기사비 · 대당">{r.status==='sold'?<select aria-label={`${r.model} ${r.id} 기사비`} disabled={busy} value={r.labor} onChange={e=>void save('labor',Number(e.target.value),r.id)}>{[80000,90000,100000].map(n=><option key={n} value={n}>{n/10000}만 원</option>)}</select>:won(r.labor)}{r.quantity>1&&<small>합계 {won(r.labor*r.quantity)}</small>}</td><td data-label="예상이익"><b>{r.status==='sold'?won(r.profit):'집계 제외'}</b></td></tr>)}</tbody></table></div>{!rows.length&&<div className={s.smallEmpty}>{data?'이달의 판매 내역이 없습니다. 상담 완료·주문 결제 후 자동으로 나타납니다.':'자동 집계를 불러오는 중…'}</div>}</section>
    <section className={s.panel}><div className={s.sectionTitle}><h2>모델별 판매가·예상이익</h2><select aria-label="수익 모델 브랜드" value={brand} onChange={e=>setBrand(e.target.value)}><option value="">전체 브랜드</option>{['경동나비엔','귀뚜라미','린나이'].map(b=><option key={b}>{b}</option>)}</select></div><p className={s.hint}>현재 홈페이지 상담기의 기본 조건 견적과 네이버 최근 실제 판매가를 따로 표시합니다. 기사비 {data?(data.defaultLabor/10000):8}만 원 기준입니다.</p><div className={s.tableScroll}><table className={`${s.table} ${s.mobileCards}`}><thead><tr><th>모델</th><th>매입 원가</th><th>홈페이지 견적</th><th>홈페이지 예상이익</th><th>네이버 최근 판매 / 이익</th></tr></thead><tbody>{data?.models.filter(m=>!brand||m.brand===brand).map(m=><tr key={m.sku}><td data-label="모델"><b>{m.brand}</b><small>{m.model}</small></td><td data-label="매입 원가">{won(m.cost)}</td><td data-label="홈페이지 견적">{range(m.web)}</td><td data-label="홈페이지 예상이익"><b>{range(m.webProfit)}</b></td><td data-label="네이버 판매 / 이익">{m.naver===null?(data.naverConnected?'판매 내역 없음':'연결 대기'):<>{won(m.naver)}<small>이익 {won(m.cost===null?null:m.naver-m.cost-data.defaultLabor)}</small></>}</td></tr>)}</tbody></table></div><details className={s.hint}><summary>가격·원가 적용 기준</summary><p>홈페이지 상담기와 같은 가격 계산을 사용합니다. 상담기에 없는 용량은 ‘견적 확인’으로 표시합니다. 네이버 가격은 홈페이지 가격으로 대체하지 않습니다. 원가는 2026-08-22 단가표의 브랜드·종류·용량 기준 참고값이며, 정확한 모델·부가세·포함 품목 확인이 필요합니다. 수수료·자재·광고비·세금 등은 이익에서 아직 차감되지 않았습니다. 판매 1대당 설치 1건으로 기사비를 계산합니다.</p></details></section>
  </div>;
}
