import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { boilerGuides, getBoilerGuide } from "../data";\nimport SeoKeywordLinks from "../../components/SeoKeywordLinks";
import GuideSeoDetails from "../GuideSeoDetails";
import styles from "../../regions/regions.module.css";

export function generateStaticParams(){return boilerGuides.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const guide=getBoilerGuide((await params).slug);if(!guide)return{};return{title:guide.title,description:guide.description,keywords:guide.keywords,alternates:{canonical:`/guides/${guide.slug}`},openGraph:{title:`${guide.title} | 로켓보일러`,description:guide.description,images:[{url:"/boiler-installation-guide.jpg",width:1680,height:945,alt:"보일러 설치 환경 안내 일러스트"}]}};}
export default async function GuidePage({params}:{params:Promise<{slug:string}>}){const guide=getBoilerGuide((await params).slug);if(!guide)notFound();return <main className={styles.shell}><nav className={styles.nav}><Link href="/" className={styles.brand}>ROCKET BOILER</Link><Link href="/guides" className={styles.navLink}>교체 가이드</Link></nav><section className={styles.hero}><p className={styles.eyebrow}>ROCKET BOILER GUIDE</p><h1>{guide.title},<br/><em>설치 조건까지 확인하세요</em></h1><p className={styles.lead}>{guide.headline}. {guide.description}</p><div className={styles.actions}><Link href="/" className={styles.primary}>사진 견적·설치 예약</Link><a href="#check" className={styles.secondary}>확인 항목 보기</a></div></section><figure className={styles.guideVisual}><img src="/boiler-installation-guide.jpg" alt="연통, 배관, 배수구와 온도조절기를 확인하는 보일러 설치 환경 안내"/><figcaption><b>보일러 설치 환경 안내</b><span>AI로 제작한 설명용 이미지이며 실제 고객 설치 사례가 아닙니다.</span></figcaption></figure><GuideSeoDetails slug={guide.slug}/><section className={styles.section} id="check"><p className={styles.kicker}>꼭 확인할 항목</p><h2>{guide.title}<br/>핵심 체크리스트</h2><div className={styles.grid}>{guide.points.map((point,index)=><article key={point.title}><b>{String(index+1).padStart(2,"0")}</b><h3>{point.title}</h3><p>{point.text}</p></article>)}</div></section><section className={styles.keywordBand}><p>함께 확인하면 좋은 보일러 정보</p><SeoKeywordLinks currentGuideSlug={guide.slug}/></section><section className={styles.section}><p className={styles.kicker}>사진 견적 준비</p><h2>사진이 있으면<br/>더 정확하게 확인됩니다</h2><div className={styles.faq}><details open><summary>어떤 사진이 필요한가요?</summary><p>보일러 전체, 모델명 라벨, 하단 배관, 연통 연결부와 배수구 위치를 촬영해 주세요. 각방제어 사용 시 조절기 사진도 함께 필요합니다.</p></details><details><summary>사진만으로 가격이 확정되나요?</summary><p>대부분의 설치 조건을 확인할 수 있지만 숨은 배관 상태나 특수 위치는 현장 확인이 필요할 수 있습니다. 추가 작업은 진행 전에 안내합니다.</p></details></div></section><section className={styles.cta}><p>{guide.title} 상담이 필요하신가요?</p><h2>오른쪽 아래 설치 예약에서<br/>사진과 희망 날짜를 남겨주세요.</h2><Link href="/">설치 예약 시작</Link></section><footer className={styles.footer}><Link href="/guides">가이드 전체 보기</Link><Link href="/brands">브랜드 비교</Link><Link href="/regions">설치 지역</Link><span>로켓보일러</span></footer></main>}
