import {createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual} from 'node:crypto';

export const SITE_HOST='rocketboiler.vercel.app';
export const CUSTOMER_ID='6409045845';
export const LOGIN_CUSTOMER_ID='7095577125';
const API_VERSION='v25';
const REDIRECT_URI=`https://${SITE_HOST}/api/admin/google-ads/oauth/callback`;
type Token={refreshToken:string};

function required(name:string){const value=process.env[name]?.trim();if(!value)throw Error(`Google Ads ${name} 설정이 없습니다.`);return value;}
function encryptionKey(){return createHash('sha256').update('google-ads:'+required('DATABASE_URL')).digest();}
export function encryptToken(token:Token){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv);const data=Buffer.concat([cipher.update(JSON.stringify(token)),cipher.final()]);return [iv,cipher.getAuthTag(),data].map(v=>v.toString('base64url')).join('.');}
export function decryptToken(value:string):Token{const [iv,tag,data]=value.split('.').map(v=>Buffer.from(v,'base64url'));const cipher=createDecipheriv('aes-256-gcm',encryptionKey(),iv);cipher.setAuthTag(tag);return JSON.parse(Buffer.concat([cipher.update(data),cipher.final()]).toString());}

function stateSecret(){return required('GOOGLE_ADS_OAUTH_STATE_SECRET');}
export function oauthState(){const payload=Buffer.from(JSON.stringify({exp:Date.now()+10*60_000,nonce:randomBytes(16).toString('hex')})).toString('base64url');const signature=createHmac('sha256',stateSecret()).update(payload).digest('base64url');return `${payload}.${signature}`;}
export function validState(value:string){try{const [payload,signature]=value.split('.');const expected=createHmac('sha256',stateSecret()).update(payload).digest(),supplied=Buffer.from(signature,'base64url');if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))return false;const decoded=JSON.parse(Buffer.from(payload,'base64url').toString());return typeof decoded.exp==='number'&&decoded.exp>Date.now()&&decoded.exp<Date.now()+11*60_000;}catch{return false;}}
export function authorizationUrl(){const params=new URLSearchParams({client_id:required('GOOGLE_ADS_CLIENT_ID'),redirect_uri:REDIRECT_URI,response_type:'code',scope:'https://www.googleapis.com/auth/adwords',access_type:'offline',prompt:'consent',include_granted_scopes:'true',state:oauthState()});return `https://accounts.google.com/o/oauth2/v2/auth?${params}`;}
export async function exchangeCode(code:string){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:required('GOOGLE_ADS_CLIENT_ID'),client_secret:required('GOOGLE_ADS_CLIENT_SECRET'),redirect_uri:REDIRECT_URI,grant_type:'authorization_code'}),cache:'no-store',signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok||typeof data.refresh_token!=='string')throw Error('Google Ads 승인 토큰을 받지 못했습니다. 다시 연결해 주세요.');return {refreshToken:data.refresh_token} as Token;}
async function accessToken(token:Token){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:required('GOOGLE_ADS_CLIENT_ID'),client_secret:required('GOOGLE_ADS_CLIENT_SECRET'),refresh_token:token.refreshToken,grant_type:'refresh_token'}),cache:'no-store',signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok||typeof data.access_token!=='string')throw Error('Google Ads 재승인이 필요합니다.');return data.access_token as string;}
async function api(token:Token,path:string,body:unknown){const bearer=await accessToken(token);const headers:Record<string,string>={'content-type':'application/json',authorization:`Bearer ${bearer}`,'login-customer-id':process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID||LOGIN_CUSTOMER_ID};if(process.env.GOOGLE_ADS_DEVELOPER_TOKEN)headers['developer-token']=process.env.GOOGLE_ADS_DEVELOPER_TOKEN;const response=await fetch(`https://googleads.googleapis.com/${API_VERSION}${path}`,{method:'POST',headers,body:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok){const raw=JSON.stringify(data?.error||{});if(/CLOUD_PROJECT_NOT_APPROVED_FOR_PRODUCTION|ACTION_NOT_PERMITTED/.test(raw))throw Error('Google Cloud 프로젝트의 제품계정 API 권한 승인이 필요합니다.');throw Error(`Google Ads API 조회 실패 (${response.status})`);}return data;}
type AdsRow={campaign?:{id?:string;name?:string;status?:string;biddingStrategyType?:string};campaignBudget?:{amountMicros?:string|number};metrics?:Record<string,string|number|undefined>};
function rows(data:unknown):AdsRow[]{if(!Array.isArray(data))return [];return data.flatMap(part=>{if(!part||typeof part!=='object'||!('results' in part)||!Array.isArray(part.results))return [];return part.results as AdsRow[];});}
const num=(v:unknown)=>Number(v)||0;
export async function campaigns(token:Token){const customer=process.env.GOOGLE_ADS_CUSTOMER_ID||CUSTOMER_ID;const query=`SELECT campaign.id, campaign.name, campaign.status, campaign.advertising_channel_type, campaign.bidding_strategy_type, campaign_budget.amount_micros, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, metrics.average_cpc, metrics.search_impression_share, metrics.search_rank_lost_impression_share, metrics.search_budget_lost_impression_share, metrics.search_top_impression_share, metrics.search_absolute_top_impression_share FROM campaign WHERE campaign.status != 'REMOVED' AND segments.date DURING LAST_30_DAYS`;const data=await api(token,`/customers/${customer}/googleAds:searchStream`,{query});return rows(data).map(row=>({id:String(row.campaign?.id||''),customerId:customer,name:String(row.campaign?.name||''),status:String(row.campaign?.status||'PAUSED'),budget:num(row.campaignBudget?.amountMicros)/1_000_000,metrics:{impressions:num(row.metrics?.impressions),clicks:num(row.metrics?.clicks),cost:num(row.metrics?.costMicros)/1_000_000,conversions:num(row.metrics?.conversions),averageCpc:num(row.metrics?.averageCpc)/1_000_000},position:{impressionShare:num(row.metrics?.searchImpressionShare),rankLostShare:num(row.metrics?.searchRankLostImpressionShare),budgetLostShare:num(row.metrics?.searchBudgetLostImpressionShare),topShare:num(row.metrics?.searchTopImpressionShare),absoluteTopShare:num(row.metrics?.searchAbsoluteTopImpressionShare)},biddingStrategy:String(row.campaign?.biddingStrategyType||'UNKNOWN')})).filter(c=>c.id&&c.name);}
export async function setCampaignStatus(token:Token,id:string,status:'ENABLED'|'PAUSED',expected:string){if(!/^\d+$/.test(id))throw Error('Google Ads 캠페인 ID를 확인해 주세요.');const list=await campaigns(token),campaign=list.find(c=>c.id===id);if(!campaign)throw Error('로켓보일러 광고계정의 캠페인만 변경할 수 있습니다.');if(campaign.status!==expected)throw Error('광고 상태가 바뀌었습니다. 새로고침 후 다시 선택해 주세요.');const customer=process.env.GOOGLE_ADS_CUSTOMER_ID||CUSTOMER_ID;await api(token,`/customers/${customer}/campaigns:mutate`,{operations:[{update:{resourceName:`customers/${customer}/campaigns/${id}`,status},updateMask:'status'}]});return {id,status};}
