export const SITE_HOST='rocketboiler.vercel.app';
const DEFAULT_CUSTOMERS=['6709381450','7095577125'];

function parsePayload(text:string,contentType=''){if(!text.trim())return null;if(!contentType.includes('text/event-stream'))return JSON.parse(text);const messages=text.split(/\r?\n/).filter(line=>line.startsWith('data:')).map(line=>line.slice(5).trim()).filter(line=>line&&line!=='[DONE]').map(line=>{try{return JSON.parse(line);}catch{return null;}}).filter(Boolean);return messages.findLast(message=>message.result||message.error||message.id)||null;}
async function rpc(url:string,body:unknown,sessionId=''){const headers:Record<string,string>={'content-type':'application/json',accept:'application/json, text/event-stream'};if(sessionId)headers['mcp-session-id']=sessionId;const response=await fetch(url,{method:'POST',headers,body:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(20000)});const text=await response.text();if(!response.ok)throw Error(`Google Ads 연결 실패 (${response.status})`);return {sessionId:response.headers.get('mcp-session-id')||sessionId,payload:parsePayload(text,response.headers.get('content-type')||'')};}
export async function client(){const url=process.env.PIPEBOARD_GOOGLE_ADS_MCP_URL?.trim();if(!url)throw Error('Google Ads 연결 정보가 없습니다.');let id=1;const init=await rpc(url,{jsonrpc:'2.0',id:id++,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'rocketboiler-admin',version:'1.0.0'}}});let session=init.sessionId;await rpc(url,{jsonrpc:'2.0',method:'notifications/initialized',params:{}},session);return {async call(name:string,args:Record<string,unknown>){const response=await rpc(url,{jsonrpc:'2.0',id:id++,method:'tools/call',params:{name,arguments:args}},session);session=response.sessionId;if(response.payload?.error)throw Error(response.payload.error.message||`${name} 호출 실패`);const result=response.payload?.result;if(result?.isError){const message=(result.content||[]).map((item:{text?:string})=>item.text||'').filter(Boolean).join(' ');throw Error(message||`${name} 호출 실패`);}const text=(result?.content||[]).find((item:{type?:string})=>item.type==='text')?.text||'{}';try{return JSON.parse(text);}catch{return {raw:text};}}};}
function customers(){const configured=(process.env.GOOGLE_ADS_CUSTOMER_IDS||'').split(',').map(v=>v.replace(/\D/g,'')).filter(Boolean);return [...new Set([...configured,...DEFAULT_CUSTOMERS])];}
function collectUrls(value:unknown,found:string[]=[]){if(typeof value==='string'&&/^https?:\/\//i.test(value))found.push(value);else if(Array.isArray(value))value.forEach(item=>collectUrls(item,found));else if(value&&typeof value==='object')Object.values(value).forEach(item=>collectUrls(item,found));return found;}
function isSiteUrl(value:string){try{return new URL(value).hostname===SITE_HOST;}catch{return false;}}
export async function scopedCampaigns(api:Awaited<ReturnType<typeof client>>){const scoped:{customerId:string;campaign:Record<string,unknown>}[]=[];for(const customerId of customers()){let payload;try{payload=await api.call('get_google_ads_campaigns',{customer_id:customerId});}catch{continue;}for(const campaign of Array.isArray(payload?.campaigns)?payload.campaigns:[]){const name=String(campaign.name||'');let matched=/로켓\s*보일러|rocket\s*boiler/i.test(name);try{const ads=await api.call('get_google_ads_ads',{customer_id:customerId,campaign_id:String(campaign.id)});matched=matched||collectUrls(ads).some(isSiteUrl);}catch{matched=Boolean(matched);}if(matched)scoped.push({customerId,campaign});}}return scoped;}
export function metric(source:Record<string,unknown>|undefined,key:string){const value=source?.[key];return value===undefined||value===null?0:Number(value)||0;}
