import {NextRequest,NextResponse} from 'next/server';
import {database,initialize} from '../operations/store';
import {authorizationUrl,campaigns,decryptToken,setCampaignStatus,SITE_HOST} from './client';
export const runtime='nodejs';export const maxDuration=60;
const authorized=(r:NextRequest)=>Boolean(process.env.ADMIN_PASSWORD&&r.headers.get('authorization')===`Bearer ${process.env.ADMIN_PASSWORD}`);
const failure=(e:unknown)=>NextResponse.json({error:e instanceof Error?e.message:'Google Ads 정보를 불러오지 못했습니다.'},{status:502});
async function token(){await initialize();const sql=database();const found=await sql`SELECT encrypted FROM boiler_integrations WHERE name='google_ads_oauth'`;return found.length?decryptToken(found[0].encrypted):null;}
export async function GET(r:NextRequest){if(!authorized(r))return NextResponse.json({error:'관리자 로그인이 필요합니다.'},{status:401});try{const saved=await token();if(!saved)return NextResponse.json({connected:false,siteHost:SITE_HOST,campaigns:[]},{headers:{'Cache-Control':'private, no-store'}});return NextResponse.json({connected:true,siteHost:SITE_HOST,campaigns:await campaigns(saved),updatedAt:new Date().toISOString()},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return failure(e);}}
export async function POST(r:NextRequest){if(!authorized(r))return NextResponse.json({error:'관리자 로그인이 필요합니다.'},{status:401});try{const body=await r.json();if(body.action==='connect')return NextResponse.json({url:authorizationUrl()});if(!['enable','pause'].includes(body.action)||typeof body.campaignId!=='string'||typeof body.expectedStatus!=='string')return NextResponse.json({error:'광고 설정을 확인해 주세요.'},{status:400});const saved=await token();if(!saved)return NextResponse.json({error:'Google Ads 계정을 먼저 연결해 주세요.'},{status:409});const status=body.action==='enable'?'ENABLED':'PAUSED';return NextResponse.json({ok:true,...await setCampaignStatus(saved,body.campaignId,status,body.expectedStatus)});}catch(e){return failure(e);}}
